
const questions = [
    /** 1 */"Vi setter i gang for folket vil feste. Hvem vil mest sannsynlig en podcast gjeste?", /** */
    /** 2 */"Festen krever at promillen må øke. Hvem kommer i natt sin eks til å besøke?",
    /** 3 */"Ekser er ekser for en grunn. Kast boksen til den som alltid er på bunn.",
    /** 4 */"Du er lat og liker ikke å jobbe. Hvem i rommet lar seg lettest mobbe?",
    /** 5 */"Et offer er du ikke. Boksen skal videre til den i rommet med det beste 'pul meg' blikket.",
    /** 6 */"Du ville nok droppet vorset for et ligg. Hvem i rommet er drit digg?",
    /** 7 */"Digg er vel å ta litt i. Kast boksen til den som alltid har en på si.",
    /** 8 */"Sjonglere kan du absolutt. Hvem er på dansegulvet til kveldens slutt?",
    /** 9 */"Du danser kanskje, men rytme har du ikke. Hvem klarer ikke dra på byen uten å gnikke?",
    /** 10 */"Fy på deg, hold henda for deg selv. Kast boksen til den som oftest tar seg en prell.",

    /** 11 */"Ikke rart økonomien din er ræva. Hvem i rommet logger mest på strava?",
    /** 12 */"Greit du liker å skryte over dine løpevaner. Hvem i rommet står oftest i vinduet å spaner?",
    /** 13 */"Slutt å være en jævla creep. Kast boksen til den som alltid blir fornærmet, det er virkelig ikke så deep.",
    /** 14 */"Du tar kanskje alt til hjerte. Hvem i rommet liker smerte?",
    /** 15 */"Pisken sier du aldri nei til. Kast nå boksen til den som er mest vill.",
    /** 16 */"Ja, du liker kanskje å tro at du er på kanten. Hvem i rommet blir den kuleste onkelen/tanten?",
    /** 17 */"Du skaffer vel alk til hele gjengen. Kast boksen til den som oftest knekker sengen.",
    /** 18 */"Sengene knekker like lett som deg. Boksen skal videre til den som alltid forlater vorset i en fei.",
    /** 19 */"Du klarer aldri helt å nå mål. Hvem i rommet står for mest gnål?",
    /** 20 */"Yappingen din tar aldri slutt. Hvem varer ikke lenger enn ett minutt?",

    /** 21 */"Du må gjerne jobbe litt med stamina. Hvem blir flau bare man nevner ordet 'vagina'?",
    /** 22 */"Du rødmer kanskje nå, men det er snart forbi. Kast boksen til den som foretrekker å gi.",
    /** 23 */"Trist for deg som aldri får. Hvem i rommet krever mest komfort?",
    /** 24 */"Så jævlig boogie du skal være. Kast boksen til den med minst blære.",
    /** 25 */"Jævlig irr at du alltid må do. Boksen skal nå kastes til den som eier de styggeste sko.",
    /** 26 */"Ta det ikke for tungt min venn. Hvem i rommet har ligget med flest MENN",
    /** 27 */"Jo eldre, jo bedre, vil du kanskje påstå. Kast boksen til den som flest lovbrudd vil begå.",
    /** 28 */"Du liker å leke kriminell. Hvem i rommet har ikke lappen på manuell.",
    /** 29 */"Det er kanskje vanskelig å kjøre bil. Kast bopksen til den som er minst stabil.",
    /** 30 */"Humøret ditt svinger mer enn en huske. Hvem i rommet spiller spill kun for å fjuske?",

    /** 31 */"Ja, deg kan man vel aldri helt stole på. Kast boksen til den som får kvelden opp til et nytt nivå.",
    /** 32 */"Ikke bli cocky, det er ikke digg. Hvem i rommet sier aldri nei til en sigg?",
    /** 33 */"Lungene dine er vel ikke helt friske. Gi boksen videre til den som ikke helt har forstått hva det vil si å hviske.",
    /** 34 */"Du er nok ikke helt diskret. Hvem i rommet står oftest på kne?",
    /** 35 */"Ditt arbeid fører vel snart til et frieri. Gi boksen videre til den som foretrekker å ri.",
    /** 36 */"Heldig er den som deg får oppleve. Hvem drar på byen for å tiltrekke seg en knyttneve?",
    /** 37 */"Dra til trynet ditt er smittsomt. Hvem må nå sørge for at glasset sitt står tomt?",
    /** 38 */"Gratulerer, nå er det bare å holde det nede. Kast boksen til den som vil ha sex med noen tilstede.",
    /** 39 */"Kanskje du må lage en sextape, så alle får se. Hvem i rommet får én i rumpa i ny og ne?",
    /** 40 */"Vi klandrer ingen, det kan være digg det. Kast boksen til den i rommet med ADHD.",

    /** 41 */"Fokus nå, vi skal videre til neste. Hvem vil helst dine grenser teste?",
    /** 42 */"Pass på nå, ikke gå for langt. Kast boksen videre til en som foretrekker at hullet er trangt.",
    /** 43 */"De merker svært lite ved din entré. Gi boksen til den som synes å ligge med yngre er en suksess.",
    /** 44 */"Håper du stopper letingen før alderen blir farlig lav. Hvem i rommet har høyest krav?",
    /** 45 */"Ikke vær så kresen at du ender opp alene. Hvem i gjengen er best på å forene?",
    /** 46 */"Det sies at felles hat er det sterkeste limet. Velg nå ut 3 stk for å danne det beste teamet.",
    /** 47 */"Dere tre som nå er utvalgt. Drikk nå til dere har drukket alt. Første som glasset tømmer, kan kaste boksen videre til gjengens forhåndsdømmer",
    /** 48 */"Det hjelper litt om du gir folk en sjanse. Gi nå boksen videre til den som forlater byen i ambulanse.",
    /** 49 */"Uff og uff, ikke skad deg for mye. Kast nå boksen til den som oftest tar seg bryet.",
    /** 50 */"Takk gud for at du orker. Boksen skal så videre til den som høyest snorker.",

    /** 51 */"Volumet må ned, barna prøver å sove. Hvem i rommet er alt for grove?",
    /** 52 */"Politisk korrekt er du ikke. Kast nå boksen til den som er oppe å nikke.",
    /** 53 (legg til animasjon)*/"Det skal hvertfall ikke stå på promillen. Kast nå boksen til den som må ut i ilden! \n\n (HOTSEAT)",
    /** 54 */"Ble det varmt her eller er det bare meg? Hvem i rommet klarer aldri å si nei?",
    /** 55 */"Dumt du ikke klarer å si ifra. Kast nå boksen til den som liker å bli kalt pappa.",
    /** 56 */"Litt rart er det vel. Gi den videre til den som har livet på stell.",
    /** 57 */"Det somn skjer det skjer. Hvem i rommet sørger for at alle ler?",
    /** 58 */"Så morsom er du ikke. Kast nå boksen til en som ikke vil rikke.",
    /** 59 */"Du er sta så det holder. Hvem i rommet klarer ikke å holde på forholder?",

    /** 60 */"Dumt ingen holder ut. Hvem står klar etter ligget med klut?",
    /** 61 */"Fint at du rydder opp etter deg selv. Kast boksen nå til den 'uskyldige' som gjemmer en rebell.",
    /** 62 */"Din evne til kamuflasje er solid. Gi boksen til den som tidligst blir gravid.",
    /** 63 */"Bruk kondom, det er nok lurest. Hvem i rommet går oftest i protest?",
    /** 64 */"Av og til kan du la den ligge. Hvem ser en snusboks, å begynner å tigge?",
    /** 65 */"Kjøp din egen, ikke bom av alle. Kast nå boksen til den har lettest for å falle (romatisk).",
    /** 66 */"Du er en håpløs romatiker, med vekt på håpløs. Gi nå boksen til den i rommet som er mest ambisiøs.",
    /** 67 */"Bra du har mål og mening. Kast boksen til den som oftest er på trening.",
    /** 68 */"Du lever nok lenger enn oss andre. Hvem vil med alkohol i blodet seg selv forandre?",
    /** 69 */"Du er nesten ikke til å kjenne igjen. Hvem skriver melding til eksen i fylla og trykker 'send'?",

    /** 70 */"Det kommer du nok til å angre på dagen etter. Kast boksen til den i rommet som lettest skvetter.",
    /** 71 */"Ingen grunn til å være redd. Boksen må nå videre til den som får flest ben spredd.",
    /** 72 */"Du er nok litt av en sjarmør. Hvem i rommet ankommer nachet i best humør?",
    /** 73 */"Det er sikkert og visst at du er glad i fylla. Hvem i rommet når ikke opp til den øverste hylla?",
    /** 74 */"Synd du ikke kan ta alle karusellene på tusenfryd. Hvem mistet først sin dyd?",
    /** 75 */"Det ryktes at du var tidlig ute. Kast nå boksen til den som er best til å prute.",
    /** 76 */"Ikke faen at du bruker mer penger enn du må. Hvem i rommet sliter mest dagen derpå?",
    /** 77 */"Det er ikke synd i deg, det var ditt eget valg. Kast nå boksen til den i rommet som bare handler på salg.",
    /** 78 */"Det må jo hamstres når det er '6 for 5'. Hvem i rommet vil du helst bli med hjem?",
    /** 79 */"Kanskje får også du litt kos. Boksen skal nå videre til den som neppe kan tros.",

    /** 80 */"Ikke alt du sier er sant. Hvem leker mest med sin tissefant?",
    /** 81 */"Bra at du koser deg. Hvem ville sett best ut på en boks med leverpostei?",
    /** 82 */"Fint for deg at du er fotogen. Kast så boksen til den som alltid er sen.",
    /** 83 */"Kjapp deg, det er slitsomt å vente. Hvem blir ved synet av tær sykt tente?",
    /** 84 */"Gjem tærne alle sammen. Hvem vil på første date slukke flammen?",
    /** 85 */"Ikke mist håpet, du får nok teken snart. Boksen skal videre til den som har sørget for at det nedentil er bart.",
    /** 86 */"Dumt for deg at du ikke får deg noe. Hvem i rommet har dans i blodet?",
    /** 87 */"Du kan å riste, det er klart. Kast nå boksen til den i rommet som tror de er super smart.",
    /** 88 */"Du burde kanskje ha litt selvinnsikt. Boksen skal videre til den som alltid følger sin plikt.",
    /** 89 */"Man trenger ikke alltid gjøre som fortalt. Gi boksen videre til den som liker å bli kvalt.",

    /** 90 */"Du er nok ikke alene om dette. Hvem i rommet vil ved synet av vekterne på bussen begynne å svette?",
    /** 91 */"Ta det med ro, de ser deg hvertfall nå. Kast boksen til den som tidligst blir grå.",
    /** 92 */"Får håpe du fortsatt har noen år. Boksen skal videre til den som rykter oftest sår.",
    /** 93 */"Det er klart du liker å spre ordet. Hvem danser oftest på bordet?",
    /** 94 */"Pass på så du ikke faller. Hvem i rommet har størst baller?",
    /** 95 */"Du er nok bare tøff for å imponere. Kast boksen til den som alltid må konkurrere.",
    /** 96 */"Kanksje ukjent for deg, men vi andre foretrekker Fair-Play. Boksen skal nå videre til den som litt for ofte sier 'slay'.",
    /** 97 */"Du burde nok jobbe litt med dine ordvalg. Hvem, i mørketiden, legger seg selv ut for salg?",
    /** 98 */"Det er ikke så morsomt å sove alene når det er kaldt. Boksen skal nå videre til den som legger igjen sitt rot overalt.",
    /** 99 */"Ikke så kult å være en rotekopp. Kast boksen til den som burde bruke en kondom på sin snopp.",
    /** 100 */"Smitt ikke med dine kjønnssykdommer. Alle kan nå tømme glasset, for byen VI KOMMER'.",

]

export default questions;